### PR TITLE
Ignore query strings in the hcaptcha spend/issue urls

### LINKED ISSUE #224: hCaptcha passes not working
**Describe the bug**
As seen in the screenshot, I do have hCaptcha passes but the the [webpage](https://forum.xda-developers.com) is still asking me for captcha.
image

**To Reproduce**
1. Open https://forum.xda-developers.com

**Expected behavior**
I should be able to visit the website without verifying the captcha if I have passes for the captcha.

**System (please complete the following information):**
 - OS: Microsoft Windows 10 (Version 10.0.19042.867)
 - hCaptcha tokens
 - Browser: Firefox
 - Browser Version: 89.0a1 (2021-04-03) (64-bit)
 - Privacy Pass Version: 2.0.8
 - Add-on installed from Mozilla's add-on store

### PR DESCRIPTION
**Pull request by ppopth**
This resolved #224 #225 #226

### CODE REVIEW

**Review by armfazh — APPROVED** [review]
it works with hcaptcha.

File: src/ext/config.js [hunk 1]
```diff
@@ -179,8 +180,16 @@ function hcBaseConfig() {
...
-    hcConfig["spend-action"]["urls"] = ["https://*.hcaptcha.com/getcaptcha", "https://*.hmt.ai/getcaptcha", "http://127.0.0.1/getcaptcha"];
-    hcConfig["issue-action"]["urls"] = ["https://*.hcaptcha.com/checkcaptcha/*", "https://*.hmt.ai/checkcaptcha/*", "http://127.0.0.1/checkcaptcha/*"];
+    hcConfig["spend-action"]["urls"] = [
+        /^https:\/\/(.*\.)?hcaptcha\.com\/getcaptcha(\?.*)?$/,
+        /^https:\/\/(.*\.)?hmt\.ai\/getcaptcha(\?.*)?$/,
+        /^https:\/\/127\.0\.0\.1\/getcaptcha(\?.*)?$/,
+    ];
+    hcConfig["issue-action"]["urls"] = [
+        /^https:\/\/(.*\.)?hcaptcha\.com\/checkcaptcha(\/.*)?$/,
+        /^https:\/\/(.*\.)?hmt\.ai\/checkcaptcha(\/.*)?$/,
```
Comment (Lekensteyn) [inline src/ext/config.js:190]: `.*` might also match `https://example.com/.hmt.ai/checkcaptcha`, let's try to avoid that with this tweak:
```suggestion
        /^https:\/\/([^/]*\.)?hmt\.ai\/checkcaptcha(\/.*)?$/,
```

This applies to all previous regexes as well. Previously wildcards were replaced by `[^\\/]*` via utils.js.

**Review by Lekensteyn — CHANGES_REQUESTED** [review]
Looks reasonable except two things:

* The regex is too broad
* docs/CONFIG.md needs to be updated since its meaning has changed.

I wonder whether we should actually add the full flexibility of regexes to the config format? As alternative, the query string could be stripped, or multiple patterns could be added.

The advantage of that is that the config change does not have to change. A regex is not a valid type in JSON, so changing from a string to a RegExp object can be somewhat problematic.

**Review by Lekensteyn — APPROVED** [review]
LGTM Thanks!
